# Generated by Django 3.2 on 2021-04-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210418_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
